STM_bj:
  path: "./test_data/STM-bj"
  realtime: false
  extract_data:
    length: 1000
    upper: 3.2
    lower: 0.000001
    method: "pull"
  hist_G:
    xlim: [0.00001, 3.16]
    num_bin: 550
    x_scale: "log"
  hist_GS:
    xlim: [-0.3, 0.5]
    ylim: [0.00001, 3.16]
    num_x_bin: 800
    num_y_bin: 550
    x_scale: "linear"
    y_scale: "log"
    zero_point: 0.5
    x_conversion: 800

I_Ebias:
  path: "./test_data/I_Ebias"
  segment: 4
  num_file: 10
  realtime: false
  extract_data:
    height: 1.45
    length: 1200
  noise_remove:
    V_range: 0.1
    I_max: 0.00001
  hist_GV:
    xlim: [-1.5, 1.5]
    ylim: [0.00001, 0.1]
    num_x_bin: 300
    num_y_bin: 300
    x_scale: "linear"
    y_scale: "log"
  hist_IV:
    xlim: [-1.5, 1.5]
    ylim: [0.00000000001, 0.00001]
    num_x_bin: 300
    num_y_bin: 300
    x_scale: "linear"
    y_scale: "log"
