watchdog: false  # auto load new data
dir: "data" # data collected from LabView
load_data:
  threads: null # CPU threads, default use all threads
extract_data:
  length: 1000
  upper: 2 # extract data greater then upper limit
  lower: 0.0001 # extract data less then lower limit
  method: "pull" # pull, crash, or both
histogram:
  G_max: 3.2
  G_min: 0.00001
  x_max: 1
  x_min: -1
  G_bins1: 1000
  G_bins2: 200
  x_bins2: 100
  x_conversion: 800 # ramp_rate / sampling_rate